-- Aashan ERP v5.6.0 - Customer statements and payment reminder history
create table if not exists public.payment_reminder_logs (
  id bigint generated by default as identity primary key,
  customer text not null,
  invoice_no text,
  recipient_email text,
  subject text,
  reminder_type text default 'Friendly Reminder',
  balance_due numeric(14,2) default 0,
  status text default 'Sent',
  failure_reason text,
  sent_by uuid default auth.uid(),
  sent_at timestamptz default now()
);
alter table public.payment_reminder_logs enable row level security;
drop policy if exists "authenticated payment reminder logs" on public.payment_reminder_logs;
create policy "authenticated payment reminder logs" on public.payment_reminder_logs for all to authenticated using (true) with check (true);
insert into public.email_templates (template_name, subject, body)
select 'Payment Reminder Email', 'Payment Reminder – Outstanding Balance {{balance_due}}', 'Hi {{customer_name}},\n\nThis is a friendly reminder regarding your outstanding invoice {{invoice_no}}.\n\nInvoice Date: {{invoice_date}}\nDue Date: {{due_date}}\nOriginal Amount: {{invoice_amount}}\nAmount Paid: {{amount_paid}}\nBalance Due: {{balance_due}}\nDays Overdue: {{days_overdue}}\n\nPlease disregard this message if payment has already been sent.\n\nZelle Payment: 832-210-4248\n\nThank you,\nAashan & Co LLC'
where not exists (select 1 from public.email_templates where template_name='Payment Reminder Email');
insert into public.email_templates (template_name, subject, body)
select 'Customer Statement Email', 'Statement of Account – {{customer_name}}', 'Hi {{customer_name}},\n\nPlease find your statement of account for {{statement_period}}.\n\nTotal Invoices: {{total_invoices}}\nTotal Payments: {{total_payments}}\nClosing Balance: {{closing_balance}}\n\nThank you,\nAashan & Co LLC'
where not exists (select 1 from public.email_templates where template_name='Customer Statement Email');
